# Site settings
title:       Captains-log
author:      Masha Safina
description: ":rocket: A responsive Jekyll theme based on my personal internet site"
baseurl:     "/captains-log" 
url:         "https://mashlo.github.io" 

# Social Links
email:            safe@masha.space
twitter_username: mashasafina
github_username:  mashlo

# Build settings
markdown: kramdown
permalink: pretty
